greeter/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "greeter"

urlpatterns = [
    path("", views.mainpage_view, name = "mainpage")
]

userbase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("greeter.urls")),
    path("accounts/", include("users.urls"))
]

users/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name = "login_view"),
    path("register/", views.register_view, name = "register_view"),
    path("logout/", views.logout_view, name = "logout_view"),
    path("<str:username>/", views.user_profile_view, name = "profile_view")
]

greeter/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.TextField()
    profile_picture_url = models.URLField(blank = True, default = "https://via.placeholder.com/150/ffffff/808080%20C/")
    description = models.TextField(blank = True, default = "Hello World!, こんにちは！")

    def __str__(self):
        return f"{self.user.username}'s Profile"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Username"
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Password",
        "type" : "password"
    }))

    class Meta:
        fields = "__all__"

class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Username"
    }))

    password1 = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Password",
        "type" : "password"
    }))

    password2 = forms.CharField(label="Password Confirmation", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Password Confirm",
        "type" : "password"
    }))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

greeter/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def mainpage_view(request):
    context = {
        "username" : "Anonim" if not request.user.is_authenticated else request.user.username
    }
    return render(request, "greeter/index.html", context)

users/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import RegistrationForm, LoginForm, AuthenticationForm

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from .models import Profile

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("greeter:mainpage")

def login_view(request):
    context = {
        "login_form" : LoginForm
    }

    if request.user.is_authenticated:
        return redirect("greeter:mainpage")

    if request.method == "POST":
        login_form = LoginForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect("users:profile_view",username=user.username)
        elif login_form.errors:
            context["error"] = "Invalid Username or Password."
    return render(request, "users/login.html", context)

def register_view(request):
    if request.user.is_authenticated:
        return redirect("greeter:mainpage")

    context = {
        "register_form" : RegistrationForm
    }

    if request.method == "POST":
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            new_user = authenticate(
                username = register_form.cleaned_data['username'],
                password = register_form.cleaned_data['password1']
            )
            new_profile = Profile.objects.create(
                user = new_user,
                full_name = new_user.username
            )
            login(request, new_user)

            return redirect("greeter:mainpage")
        elif register_form.errors:
            context["error"] = "Please enter valid a name and password."
    
    return render(request, "users/register.html", context)

def user_profile_view(request, username):
    user = User.objects.get(username = username)
    context = {
        "profile" : Profile.objects.get(user = user)
    }
    return render(request, "users/profile.html", context)

greeter/templates/greeter/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Manrope&display=swap" rel="stylesheet">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'greeter/css/greeter.css' %}">

    <title>Userbase</title>
  </head>
  <body class="min-vh-100 bg-secondary">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'greeter:mainpage' %}">Userbase</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <div class="ml-auto d-flex">
            {% if not request.user.is_authenticated %}
              <a class="mr-2" href="{% url 'users:register_view' %}">
                <button id="register_button_nav" class="btn btn-secondary">
                    Register
                </button>
              </a>

              <a  href="{% url 'users:login_view' %}">
                <button id="login_button_nav" class="btn btn-secondary">
                    Login
                </button>
              </a>
            {% else %}
              <a href="{% url 'users:logout_view' %}">
                <button id="logout_button_nav" class="btn btn-secondary">
                    Logout
                </button>
              </a>
            {% endif %}

            </div>
            </div>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer class="page-footer font-small blue bg-dark text-light">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            Made by Steven - 2020
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

greeter/templates/greeter/index.html
{% extends 'greeter/base.html' %}

{% block content %}
<div class="jumbotron rounded-0 text-light mb-0">
    <div class="container">
        <h1 class="display-4">Selamat Datang, {{username}}.</h1>
        <p class="lead">Apa yang anda ingin lakukan hari ini?
            {% if request.user.is_authenticated %}
            See your profile <a href="{% url 'users:profile_view' request.user.username %}">here</a>
            {% endif %}
        </p>
        <hr class="my-4">
        <p>Authentication and Users in Django.</p>
        <a class="btn btn-dark btn-lg" style href="#" role="button">Hello :)))</a>
    </div>
  </div>

  <section class="bottom-main bg-secondary content-bar text-light">
        <div class="container">
            {% if request.user.is_authenticated %}
            <h3 class="pt-4">Bukan {{username}}? <a href="{% url 'users:logout_view' %}">Logout</a></h3>
            <p>How did you get here?</p>
            {% else %}
            <h3 class="pt-4">You are not logged in, <a href="{% url 'users:login_view' %}">Login</a> now so we can greet you properly :)</h3>
            <p>OwO UwU</p>
            {% endif %}
        </div>
  </section>

{% endblock %}

users/templates/users/login.html
{% extends 'greeter/base.html' %}

{% block content %}

<section class="main-section d-flex justify-content-center align-items-center text-light">
    <form method="POST" action="{% url 'users:login_view' %}" class="login-form bg-dark rounded-lg d-flex flex-column justify-content-center p-4">
        {% if error %}
            <p class="text-center p-2 bg-danger rounded-lg">{{error}}</p>
        {% endif %}
        <h3 class="mb-3 text-center">Login here!</h3>
        {% csrf_token %}
        {{login_form}}
        <button id="btn_login" type="submit" class="btn btn-secondary mb-3">Login</button>
        <p>Don't have an account? <a href="{% url 'users:register_view' %}">Register here</a></p>
    </form>
</section>

{% endblock %}

users/templates/users/profile.html
{% extends 'greeter/base.html' %}

{% block content %}

<section class="main-section d-flex justify-content-center align-items-center text-light">
    <div class="login-form bg-dark rounded-lg d-flex flex-column align-items-center justify-content-center p-4">
        <p>Profile for user: {{profile.user.username}}</p>
        <img class="profile-img" src="{{profile.profile_picture_url}}">
        <h3 class="mt-3">{{profile.full_name}}</h3>
        <p class="text-center">{{profile.description}}</p>
    </div>
</section>

{% endblock %}

users/templates/users/register.html
{% extends 'greeter/base.html' %}

{% block content %}

<section class="registration-section d-flex justify-content-center align-items-center text-light flex-column">
    {% if error %}
            <p class="text-center p-2 bg-danger rounded-lg">{{error}}</p>
    {% endif %}
    <form method="POST" action="{% url 'users:register_view' %}" class="login-form bg-dark rounded-lg d-flex flex-column justify-content-center p-4">
        <h3 class="text-center mb-3">Register Now!</h3>
        {% csrf_token %}
        {{register_form}}
        <button type="submit" id="btn_register" class="btn btn-secondary">Register</button>
    </form>
</section>

{% endblock %}